"""
    StrainGaugeOnBar3D

An element designed to wrap around a Bar3D. The element makes no contribution 
to residual or Lagrangian besides the contribution made by the element it wraps.
`StrainGaugeOnBar3D` provides requestables allowing to model strain gauges. The
strain gauges are placed halfway along the `Bar3D`. In an inverse analysis, the
`StrainGaugeOnBar3D` is itself wraped by an `ElementCost` element.

# Keyword arguments when adding elements:

- `P` `SMatrix{3,Nsensor,𝕣}`, giving the offset between the point on the axis of the 
   element halfway along its length. `P[1,:]` must be zero.
- `D` `SMatrix{3,Nsensor,𝕣}`, the orientation of a strain gauge. If multiple strain gauges 
   are present at the same position, one can repeat the columns of `P`.
- `ElementType=Bar3D` the constructor to the wrapped element.  This is typicaly
   an `Bar3D` but could be another element wrapping an `Bar3D`.
- `elementkwargs` a `NamedTuple` with the keyword arguments to the wrapped element.  See [`Bar3D`](@ref)   

# Requestables:

- `εₐₓ` (scalar), the axial strain at the middle of the element
- `ε` a vector of length `Nsensor` containing the strain values defined by `P`
   and `D`.    

#Keyword arguments when drawing elements:

When calling `draw!`, instruction to `StrainGaugeOnBar3D` elements are given as in this example:

    draw!(axis,state>;StrainGaugeOnBar3D=(L= @SVector [0.1,0,0],point_size=10,accelerometer_color=:orange))`

The optional keword arguments and their default values are  
- `gauge_color = :blue`
- `expand      = 1.02` a multiplicative factor applied to `P` in the drawing only (not in strain calculation)
   to ensure the gauge is not hidden by a patch-drawing of the beam itself.
- `L           = SVector{Nsensor,𝕣}(norm(P)/5 for i=1:Nsensor)` the length of the strain gauge in the drawing  TODO

    
"""
struct StrainGaugeOnBar3D{Ngauge,Teleobj,Treq} <: AbstractElement
    eleobj   :: Teleobj
    req      :: Treq
    P        :: SMatrix{3,Ngauge,𝕣}  # P[1] must be zero
    D        :: SMatrix{3,Ngauge,𝕣}
    ηₙ        :: SVector{  Ngauge,𝕣}
end
function StrainGaugeOnBar3D(nod::Vector{Node};P,D, ElementType=Bar3D,elementkwargs)  # Teleobj because we may wrap wrapped bars
    req       = @request eleres(ε)
    eleobj    = ElementType(nod;elementkwargs...)
    all(P[1,:].==0.) || muscadeerror("In arguments of StrainGaugeOnBar3D, P[1,:] must all be zero")
    ηₙ         =  D[1,:].^2
    return StrainGaugeOnBar3D(eleobj,req,P,D,ηₙ)
end

Muscade.no_second_order(::Type{<:StrainGaugeOnBar3D{Ngauge,Teleobj}}) where{Ngauge,Teleobj} = Muscade.no_second_order(Teleobj)

function Muscade.doflist( ::Type{<:StrainGaugeOnBar3D{Ngauge,Teleobj}}) where{Ngauge,Teleobj} 
    Teledoflist = [Muscade.doflist(Teleobj)...]
    return (
        inod = Tuple(vcat(Teledoflist[1]...,[3,3])),
        class = Tuple(vcat(Teledoflist[2]...,[:A,:A])),
        field = Tuple(vcat(Teledoflist[3]...,[:γ₀,:γ₁])),
    )
end

@espy function Muscade.residual(o::StrainGaugeOnBar3D, X,U,A,t,SP,dbg)
    req          = mergerequest(o.req) # @espy will generate req = merge(o.req,req) where req is the additional argument of lagrangian method generated by espy
    R,FB,☼eleres = Muscade.getresidual(o.eleobj,X,U,A,t,SP,dbg,req.eleres) 
    ☼εₐₓ         = ∂0(eleres.ε)
    ☼pred_strain           = o.ηₙ .* (εₐₓ .* (1 + A[2]) + A[1])
    return R,FB
end   

# TODO Drawing a strain gauge
# function Muscade.allocate_drawing(axis,o::AbstractVector{Gauge};kwargs...) where{Gauge<:StrainGaugeOnBar3D{Ngauge}} where{Ngauge}  
#     mutt,optt    = Muscade.allocate_drawing(axis,[oᵢ.eleobj for oᵢ∈o];kwargs...)
#     args         = default{:StrainGaugeOnBar3D}(kwargs,(;)     ) 
#     opt          = default(args,(gauge_color=:lightgreen,expand=1.02,target=optt,L=1.))
#     nel          = length(o)
#     x            = 𝕣2(undef,3,3*Ngauge*nel)       # 3D, end1-end2-nan, ngauge, nel
#     rx           = reshape(x,3,3,Ngauge,nel)
#     rx[:,3,:,:] .= NaN
#     mut          = (target=mutt, gauge=x)
    
#     return mut,opt
# end
# function Muscade.update_drawing(  axis,o::AbstractVector{Gauge},oldmut,opt, Λ,X,U,A,t,SP,dbg) where{Gauge<:StrainGaugeOnBar3D{Ngauge}} where{Ngauge} 
#     X₀                   = ∂0(X)
#     nel                  = length(o)
#     rx                   = reshape(oldmut.gauge,3,3,Ngauge,nel)
#     for (iel,oᵢ) ∈ enumerate(o)
#         gp,ε,vₛₘ,rₛₘ,vₗ₂,uₗ₂,cₛₘ = kinematics{:direct}(oᵢ.eleobj,view(X₀,:,iel))
#         rx[:,1,:,iel]    = rₛₘ ∘₁ (oᵢ.P*opt.expand .+ opt.L*oᵢ.D) .+ cₛₘ
#         rx[:,2,:,iel]    = rₛₘ ∘₁ (oᵢ.P*opt.expand .- opt.L*oᵢ.D) .+ cₛₘ
#     end
#     mutt = Muscade.update_drawing(  axis,[eᵢ.eleobj for eᵢ∈o],oldmut.target,opt.target, Λ,X,U,A,t,SP,dbg) 
#     mut  = (target=mutt,gauge = oldmut.gauge )
#     return mut
# end
# function Muscade.display_drawing!(axis,::Type{<:StrainGaugeOnBar3D{Ngauge,Teleobj}},obs,opt) where{Ngauge,Teleobj}                         
#     lines!(axis,obs.gauge,color = opt.gauge_color ,linewidth=3)
#     Muscade.display_drawing!(axis,Teleobj,obs.target,opt.target)
# end